server:
  port: 6001
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/docker_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    druid:
      test-while-idle: false
  redis:
    database: 0
    host: redis
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        wait: -1ms
        max-idle: 8
        min-idle: 0
  swagger2:
    enabled: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: chouc.docker.entity
